name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true


    name: Pruebas, analisis de código y cobertura
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      # Required so Sonar posts PR checks/comments
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Sonar needs full history for PR decoration

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'  # or your version
          bundler-cache: true

      - name: Install deps
        run: bundle install --jobs 4 --retry 3

      - name: Prep reports
        run: rm -rf coverage reports && mkdir -p reports
          
      - name: Run RSpec with coverage & Sonar test report
        run: |
          mkdir -p reports
          bundle exec rspec

      - name: Show coverage.json top-level keys
        run: |
          command -v jq >/dev/null || sudo apt-get install -y jq
          jq -r 'keys' coverage/coverage.json

      - name: Upload test/coverage artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rspec-and-coverage
          path: |
            reports/sonar-test-report.xml
            coverage/coverage.json

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- Pasos de Docker ---

      - name: Set up QEMU
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
